### PR TITLE
add disqus identifier for post

### PR DESCRIPTION
**Pull request by laurentkempe**
Follows #191

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Could you use javascript naming convention : `disqusIdentifier` instead of `disqus_identifier`. All others variables in front-matter use this convention. In version 2.0, I'm gonna use python naming convention (`camel_case`) for variable in front-matter. It's more appropriate in yml.

**Comment by laurentkempe** [comment]
@LouisBarranqueiro Done!

**Comment by LouisBarranqueiro** [comment]
Sweet! Thank you man :)

**Comment by laurentkempe** [comment]
:+1:

**Pull request merged**
