### PR TITLE
HTML5 improvements - `<img>` tag must have `alt` property

### PR DESCRIPTION
**Pull request by jrbenito**
### Configuration

 - **Operating system with version** : Ubuntu
 - **Node version** : 4.4.3
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 
 
### Changes proposed

 - HTML5 validation complains about `` tag without `alt` property. This proposes to add `alt` property to author´s picture based on site´s language. PR includes EJS template modification and language files modified with new string. English, Portuguese (BR) and Spanish translations are provided but other languages need to be done.
 - Language file pt-br has a typo, an extra S in Facebook share string. Extra letter was removed.

#### Notes

All language files were modified to contain new string tag `author.picture` but only English, Portuguese-Br and Spanish translations were filled up, others are just blank strings. 

What is the standard approach in this situation?

1. Leave blank strings for untranslated strings
2. Copy English text when no translation available

Personally, I like most option 2. However I chose to go for option 1 because there are already blank strings inside language files but no untranslated text. I can do another PR with English text applied to other languages if @LouisBarranqueiro thinks option 2 is the best.

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Yeah, you are right 👍 

1. Could you move this translation under `global` object with `author_picture`. I prefer to let `author` object for author information.
2. It preferable to fill translations. Use google traduction and if a traduction is wrong, a user will notice it and PR :)

Traduction : 

- French (fr-FR) : **Photo de l'auteur**  :)

**Comment by jrbenito** [comment]
Hi @LouisBarranqueiro 

Will do and PR.

**Comment by jrbenito** [comment]
@LouisBarranqueiro 

Modified the PR, github is saying sidebar.ejs is binary file. This is happenning because my edit or it was yours? Could not determine it here yet. If it was mine, ignore the PR, I will do it again.

**Comment by LouisBarranqueiro** [comment]
I don't know, that's strange. It don't matter.

 Last thing to improve your code : you can  use `__('global.author_picture')` directly without `if` in header and about view.
``` js
<%= __('global.author_picture') %> 
```

**Comment by jrbenito** [comment]
> I don't know, that's strange. It don't matter.

I found the problem, it was some Kdiff3 bullshit. I rebased the branch and issue is gone.

**Comment by jrbenito** [comment]
@LouisBarranqueiro 

PR is up to date with your requests and sidebar.ejs back as text file instead of binary.

**Comment by LouisBarranqueiro** [comment]
perfect 👍

**Pull request merged**
