### PR TITLE
Scripts cleanup & add SRI

### PR DESCRIPTION
**Pull request by fletchto99**
This is very much a work in progress at this point. The idea is to implement SRI for all assets which are delivered via a CDN. Unfortunately, some assets are dynamic and won't support SRI, in which case CSP will be required. 

Part of this change is to use proper HTML tags with the integrity attribute instead of dynamically generating the tags during JS execution. To ensure speed I've used `async` when possible however we could also probably use `defer` to defer script loads until the page has finished parsing.

I'm wondering if the `script` template should also be responsible for loading other 3rd party scripts such as Google Analytics, Baidu Analytics, etc..

Lastly, I've also preferred that scripts load over `https` when possible instead of loading over the page's current protocol.

TODO:
- [x] ~Implement something like [grunt-sri](https://www.npmjs.com/package/grunt-sri) into the build pipeline to compute hashes for the resources we generate - probably a low priority since a compromise of javascript hosted on the same origin probably means a compromise of the blog's static content as well 🤷‍♂~ Not currently possible with Hexo's CSS helper
- [x] Move 3rd party code out of the `scripts` template and into their own templates which are then included by some `lib` or `vendor` template which is loaded in the `HEAD`? 46a8bdc

Closes: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/544

---
This change is [Reviewable](https://reviewable.io/reviews/louisbarranqueiro/hexo-theme-tranquilpeak/545)

### CODE REVIEW

**Comment by fletchto99** [comment]
@LouisBarranqueiro This should be ready for review. Unfortunately, SRI isn't possible for local resources due to Hexo's `css` and `js` helpers not supporting. That's not a major issue though since a compromise of a local CSS/JS file likely means that your blog's host is compromised. We could update the helpers but I don't have the time to do that right now and I also don't want to change the build pipeline too much.

**Comment by LouisBarranqueiro** [comment]
👋 @fletchto99 , I'm working right now on stop using hosted versions of moment, algoliaclient, gitment, etc... because it's very hard to maintain them that way. I will import them in the theme via NPM so it will be easier to track new versions and update them. Basically,  what I've done for jquery, fontawesome, etc... so we should not need that.

**Comment by fletchto99** [comment]
Perhaps if we're moving more of these libraries into the build pipeline then we can use something like https://www.npmjs.com/package/grunt-sri to compute the SRI during the build process.

**Comment by LouisBarranqueiro** [comment]
Please let's continue this conversation in https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/544

**Pull request closed without merging**
