### PR TITLE
HTML5 fixes

### PR DESCRIPTION
**Pull request by kyrylkov**
### Configuration

 - **Operating system with version** : Microsoft Windows [Version 10.0.10586]
 - **Node version** : 6.3.0
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 
 
### Changes proposed

 - Change header-title from h1 to div to prevent HTML5 validator warning and to improve SEO h1
 - Change headings to divs to prevent HTML5 validation errors about
 - Move scripts to be inside BODY 
scripts

### CODE REVIEW

**Comment by jrbenito** [comment]
@LouisBarranqueiro ,

While ago we talked about those `<h1>...<h5>' validations. At that time we did not come up with any ideas. How about this `<div>` proposition?

**Comment by LouisBarranqueiro** [comment]
Hey @kyrylkov, 

1. Removing `h4` break the style on author name. And there is no warning on it, so why do you want to replace it with a `div`?

2. It's ok for the author biography. @jrbenito, yeah wrap biography in a `div` make sense.

3. About scripts, @jrbenito PR couple of days ago to import scripts at the end of the body

**Comment by kyrylkov** [comment]
@LouisBarranqueiro 

Yes, sorry.  Removing H4 on author is an overkill.

**Comment by LouisBarranqueiro** [comment]
np, could you fix it?

**Comment by kyrylkov** [comment]
@LouisBarranqueiro fixed

**Comment by LouisBarranqueiro** [comment]
perfect 👍

**Pull request merged**
