### PR TITLE
Add support for instantclick

### PR DESCRIPTION
**Pull request by ttimasdf**
> [InstantClick](http://instantclick.io/) is a JavaScript library that dramatically speeds up your website, making navigation effectively instant in most cases.

In a word, it load the link when you move your mouse over it. Really fantastic.

* ~~There's a problem with search page, it doesn't appear(in fact when instantclick is disabled, it doesn't work as well, in my case).~~ (update: maybe because I forgot swiftype..)
* Disqus not tested, for my blog has not yet configured it.
* Google Analytics or other js's may need manual configuration.

So, currently by default it is disabled :stuck_out_tongue: But its really really great i hope it be a feature of the theme :+1:

### CODE REVIEW

**Comment by h404bi** [comment]
js file not load if `theme.instantclick` set to false would be better.
```
<% if (theme.instantclick) { %>
<%- js('assets/js/instantclick.js') %>
<% } %>
```

**Comment by ttimasdf** [comment]
Before adding instantclick to `tranquilpeakJsFilesToInject`, the file finally generated is
```
-rw-r--r--  1 tim  tim  123428 Nov 22 18:46 script.min.js
```
After adding instantclick:
```
-rw-r--r--  1 tim  tim  129483 Nov 22 18:43 script.min.js
```
121k vs 126k, which I think is not a big problem.
just too lazy coz the ejs is automatically generated according to Gruntfile which may not be easily changed.~~因为我不会~~

**Comment by h404bi** [comment]
oh I see, I forget the static files preprocessing, never mind. :hankey: ~~好吧当我没说~~

**Comment by LouisBarranqueiro** [comment]
Firstly, thank you :) I checked on the official site and it's an interresting feature. Question : How does it handle routing because it can be a problem for google analysis?

**Comment by ttimasdf** [comment]
It uses xhr to reload the page body. More explanations on the [official website](http://instantclick.io/how-it-works), and [how to solve it](http://instantclick.io/scripts). For google analytics, solution already included  in dcc9655177cee458705ddf4b81d88c028b273f7d

**Comment by LouisBarranqueiro** [comment]
I currently testing Google analytics and Disqus to integrate this feature in the next release

**Comment by LouisBarranqueiro** [comment]
Here is the bugs that I found :  
- Google analytics doesn't detect that a user go to an other page
- InstantClick capture handle request for about page, Swiftype, RSS Feed (it should ignore these routes)

Browser Error (Safari :  9.0.1)
- jQuery :  `jquery.fancybox-thumbs.js:22 -  TypeError: undefined is not an object (evaluating 'F.helpers')`
- Disqus : `postMessageembed.js:14:6174 - TypeError: a.postMessage is not a function. (In 'a.postMessage(b,c)', 'a.postMessage' is undefined)`

Could you fix this, please? Currently, I don't have time to do that.

**Comment by ttimasdf** [comment]
Sadly, all but swiftype could be fixed. I've solve the others, but swiftype still not work after page reload.

**Pull request closed without merging**
