### PR TITLE
improved Russian translate

### PR DESCRIPTION
**Pull request by twirlfog**

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Thank @twirlfog ! :) i'm gonna merge it in the next release

**Comment by twirlfog** [comment]
Thank you for the complete documentation. Very like.
I could not find where it is written about the installation `hexo-renderer-sass`. The `hexo` initial configuration it is not. You may want to add to the documentation?

**Comment by LouisBarranqueiro** [comment]
you don't need of this module

**Comment by twirlfog** [comment]
It does not start in server mode without this module
```bash
> hexo s
INFO  Start processing
ERROR Process failed: source/_css/layout/_blog.scss
TypeError: Cannot read property 'compile' of undefined
    at View._precompile...
```

**Comment by twirlfog** [comment]
sorry. It starts, but gives an error.

**Comment by LouisBarranqueiro** [comment]
Open an issue please, to report a bug or ask question man :)

**Comment by twirlfog** [comment]
Well, thank you for your time.

**Comment by LouisBarranqueiro** [comment]
it's an know issue. it come from Hexo, not the theme : https://github.com/hexojs/hexo/issues/1793

**Comment by LouisBarranqueiro** [comment]
Sorry man, I didn't notice that you PR on master. Could you PR on **dev** branch please?

**Pull request closed without merging**
