### PR TITLE
Update jquery to 2.2.4

### LINKED ISSUE #450: jQuery 2.2.4
Use the latest jQuery 2.x (2.2.4)

### LINKED ISSUE #452: fontawesome 4.7.0
Use fontawesome 4.7.0.

### LINKED ISSUE #453: fancybox 2.1.6
Use the latest fancybox 2 (2.1.6). 

Note that 2.1.7 is not available via bower.

### PR DESCRIPTION
**Pull request by tnir**
### Changes proposed

 - Use the latest version of jQuery 2.x (Closes #450)
 - Use the latest version of Font Awesome (Closes #452)
 - Use the latest version of fancybox 2 (Closes #453)

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Hi @tnir, what are the reasons behind these upgrades (jquery and fancybox) ?  Did you test features that depends on these libraries?

**Comment by tnir** [comment]
@LouisBarranqueiro Due to security (XSS) cf. jquery/jquery#2432, while just minor upgrade on fancybox.

What feature tests did you expect?

**Comment by LouisBarranqueiro** [comment]
The theme do not use this feature, so it is not directly concerned by this issue. Updating dependencies require to know the theme and know how to test it because unfortunately we don't have any unit tests so I will handle this.

**Comment by tnir** [comment]
@LouisBarranqueiro Thanks for the consideration.

**Pull request closed without merging**
