### PR TITLE
added FA translation

### PR DESCRIPTION
**Pull request by Mr0Null**

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Hey @Mr0Null,
Perfect for the label file. but why did you add these dependencies since you didn't commit any portion of code where these dependencies are used?

**Comment by Mr0Null** [comment]
I have added that because it is used in the RTL branch :) I may remove it from this branch :D

**Comment by LouisBarranqueiro** [comment]
yes, remove all changes of `package.json` file

**Comment by Mr0Null** [comment]
I think it's time to merge branches!

**Comment by LouisBarranqueiro** [comment]
You committed changes in `package.json` file. remove them. Just commit the label file.

**Comment by Mr0Null** [comment]
package.json recovered :D

**Comment by LouisBarranqueiro** [comment]
Great. 2 last things, I noticed that you add labels that are not in the orignal version of the theme : 
- tag 
- category
- telegram
- instagram

Could you removed them please? And could you also add translation for "Author's picture" - `author_picture` variable please ?

**Comment by Mr0Null** [comment]
I think the instagram and telegram are essential things which weren't existed there! also I just added this two! I don't know how tag and category were added :| I will correct it!

**Comment by LouisBarranqueiro** [comment]
yeah but they are not used by the original version so they are useless.

**Comment by Mr0Null** [comment]
committed

**Comment by LouisBarranqueiro** [comment]
Perfect! thanks man :)

**Comment by Mr0Null** [comment]
you're welcome!

also I have created a branch called RTL for rtl support! you can create one and merge my branch into yours

**Comment by LouisBarranqueiro** [comment]
rtl support?

**Comment by Mr0Null** [comment]
by default, you cannot write in languages with rtl direction, you need to change some scss to support it!

**Comment by LouisBarranqueiro** [comment]
oh, you are talking about `direction: rlt;`, open an issue and show me what did you modify. We will think about if we can integrate it in the theme

**Comment by Mr0Null** [comment]
I dont think it's a good idea to have both in one theme! it may cause some conflict :|

**Comment by LouisBarranqueiro** [comment]
it depends of the changes, that why I asked you to create issue to check if it possible :)

**Pull request merged**
