### PR TITLE
comment_and_share should be translated to "评论和共享" in Chinese.

### PR DESCRIPTION
**Pull request by 374632897**
### Configuration

 - **Operating system with version** : 
 - **Node version** : 
 - **Hexo version** : 
 - **Hexo-cli version** : 
 
### Changes proposed

 - the wrong translation of 'comment_and_share' in Chinese

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Hey @374632897 , what's the difference between these two translations?

**Comment by G1enY0ung** [comment]
Hey,@LouisBarranqueiro. **注释**,this word means, for example, if you have a piece of code with some extra messages to notice people somethings, the **English Word** of 注释 is **comment**. And, **评论** in English is also **comment**.Also an example, on StackOverflow, every question with lots of comments, these are 评论s.

**Comment by 374632897** [comment]
Yeah, Thanks for you @G1enY0ung , like @G1enY0ung said, in Chinese, '注释' means something you add to make it easier for others to understand, like `/*  some 注释 **/`, and '评论' means some conversations the visitor left at the bottom of posts when they have some questions or ideas want to talk with blogger,  like the service disqus provided. And  I think '评论' is better for this situation .What do you think?

**Comment by LouisBarranqueiro** [comment]
Great! Thank you guys for the explanation :)

**Pull request merged**
