### PR TITLE
Convert to github actions from travis

### PR DESCRIPTION
**Pull request by fletchto99**
This PR moves CI from Travis to [GitHub Actions](https://github.com/features/actions). There wasn't much of a motivation behind this PR aside from the fact I wanted to play with actions a bit. The action could be further improved to bundle a release when a push/merge to master is made, automating the release flow. I'll leave that up to you if you wish to do that.

Actions provides the ability to do matrix builds. In this case we're building against node 8, 10 and 12. We could also build for various operating systems though I don't believe that's necessary here.

---
This change is [Reviewable](https://reviewable.io/reviews/louisbarranqueiro/hexo-theme-tranquilpeak/599)

### CODE REVIEW

**Comment by fletchto99** [comment]
This is going to fail initially as I've added another step to run `npm audit` on the dependencies. This would ensure future PRs don't introduce new vulnerable dependencies (and will also fail when future pushed contain a vulnerable dependency). This step could be moved out into a separate `audit` action which perhaps wouldn't be required. The same could also be said for the linting step, it could be its own action.

**Comment by LouisBarranqueiro** [comment]
👋 @fletchto99 , It could be a good idea, thanks for working on that. I have a few concerns before accepting this contribution:
- could it be possible to have an alias like we have on Travis to test the code on the latest LTS node version?
- the configuration looks more verbose, anything we can simplify?
 
> This is going to fail initially as I've added another step to run `npm audit` on the dependencies

- why is it going to fail? a current dependency is vulnerable?

**Comment by fletchto99** [comment]
Here's a sample run from my fork: https://github.com/fletchto99/hexo-theme-tranquilpeak/actions/runs/3912587

> could it be possible to have an alias like we have on Travis to test the code on the latest LTS node version?

I'll look into that

> The configuration looks more verbose, anything we can simplify?

We could have all of the commands run under one name:

```
    - name: npm install, lint, build
      run: |
        npm install
        npm run lint
        npm run prod
```

but then we lose log folding. I think it makes more sense for the workflow file to be verbose this way such that the logs represent that. 

> why is it going to fail? a current dependency is vulnerable?

Yup you can see the vulnerable dependencies in the output here: https://github.com/fletchto99/hexo-theme-tranquilpeak/runs/374855020?check_suite_focus=true#step:5:4

**Comment by fletchto99** [comment]
> could it be possible to have an alias like we have on Travis to test the code on the latest LTS node version?

It looks like that action has an issue open for this enhancement: https://github.com/actions/setup-node/issues/26

**Comment by LouisBarranqueiro** [comment]
> Yup you can see the vulnerable dependencies in the output here: https://github.com/fletchto99/hexo-theme-tranquilpeak/runs/374855020?check_suite_focus=true#step:5:4

There is nothing we can do about it because this is a sub-dependency of `grunt` and this can be problematic for several other packages. Could you please remove this change from this PR? I will decide what to do separately.

Thanks for the details. I did a review of the changes. 👍

**Comment by fletchto99** [comment]
I've addressed the feedback and re-requested a review. Another cool thing you could consider in the future is having actions auto-publish when dev is merged into master (i.e. publish to the releases page)

**Comment by LouisBarranqueiro** [comment]
> Another cool thing you could consider in the future is having actions auto-publish when dev is merged into master (i.e. publish to the releases page)

I cannot deploy automatically because the production theme is built with a special config and some secrets in the this config file. It would take some time to set that up via Travis/GitHub actions. I don't want to invest time on it because it takes me literally 1s to deploy today with a button.
I don't want to deploy the production automatically.

**Comment by fletchto99** [comment]
Ah my bad!Ah my bad. I've fixed that now.

**Comment by LouisBarranqueiro** [comment]
👍 Thanks buddy!

**Pull request merged**
