### PR TITLE
Onesignal WebPush service integration

### LINKED ISSUE #387: Feature request : web push notifications
What about having something like push notifications, when a new article or something is being posted by someone .then a push notification is being send. There are many services for this

### PR DESCRIPTION
**Pull request by jrbenito**
### Configuration

 - **Operating system with version** :  Ubuntu, tested on chrome windows
 - **Node version** :  4.4.5
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 
 
### Changes proposed

 - Integrate Onesingal WebPush option by adding javascript necessary, sidebar link and modal for user permissions.
 - Still need some css makeup for beutify modal and transform  it´s links on porper beautiful buttons
 - Still need more work to support "fully https" websites
 - Need translations to other languages

Comments appreciated, help welcome

Fix #387

### CODE REVIEW

**Comment by YoshinoriN** [comment]
@jrbenito 

_config.yml are included your id and subdomain. Is it no problem??

**Comment by jrbenito** [comment]
My bad, I did a cherry pick and forget to clean up . Thanks for heads up. As soon as I get back to my PC I will remove it. 

There is no security issue because it is public placed in the HTML, just like Google Analytics ID. Even someone use my ID, onesignal only accepts push permissions request from registered domain. One still has to get his own ID. 

Thanks again

**Comment by LouisBarranqueiro** [comment]
Great! 
Could you explain me how do it works? for a reader? and for the blog owner? 
When and how do you notify readers that there is a new post?

**Comment by jrbenito** [comment]
@YoshinoriN 

Done! Thanks again.

@LouisBarranqueiro 

Rebased on dev. If you want to merge, it already works. When I have some spare time I will improve it a little more. If you need changes before merge please ask.

**Comment by LouisBarranqueiro** [comment]
You did a great job but I don't want to include all this code directly in the theme because it's justly a theme. All this code should stand in a separate npm module and integrated in the theme with only:
```
<%- partial('hexo-onesignal/lib/templates/notify', {lang: 'fr'}) %>
```
All hexo themes should be able to use your work like this. Create a node module, and notify me if you have some questions to achieve this. You should only expose the css variable names to able each theme to customize style of the modal, that's all.

**Pull request closed without merging**
