### PR TITLE
Create de-DE.yml

### PR DESCRIPTION
**Pull request by LeoWinterDE**
After failing with #349 and [deleting my pr fork](https://github.com/isaacs/github/issues/168) (A solution for the problem?) from #350 a new PR.

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Could you update your PR with changes requested in #350, please

**Comment by LeoWinterDE** [comment]
The changes from #350 are in here #398 (67e67c16c6621af510a4732a9bfc6c6929115179).

**Comment by darekkay** [comment]
There is just a small typo: `kein Title` should be `kein Titel`. Looks good otherwise :)

BTW - you don't need to create a new pull request - you can just make a new commit to your branch ;)

**Comment by LeoWinterDE** [comment]
@darekkay I now usually, but I [delete my fork ("unknown repo")](https://github.com/isaacs/github/issues/168) and did not find a solution for that problem.

Typo fix in 2c1d3c369adaafb775b3408292de33fd5da6ea60.

**Comment by LouisBarranqueiro** [comment]
Great! :)

**Pull request merged**
